spring:
  application:
    name: registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  level:
    root: INFO
server:
  port: 8761
