server:
  port: 0
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_URL:http://localhost:9092}
          zkNodes:
            - ${ZOOKEEPER_URL:http://localhost:2181}
      bindings:
        input:
          destination: external-message
          content-type: application/json
          group: external-message-group-1